namespace Microsoft.EntityFrameworkCore.Query;

public class TPCFiltersInheritanceQueryNpgsqlTest(TPCFiltersInheritanceQueryNpgsqlFixture fixture)
    : TPCFiltersInheritanceQueryTestBase<TPCFiltersInheritanceQueryNpgsqlFixture>(fixture);
